[package]
name = "rust-game"
version = "0.0.1"
authors = ["AXDOOMER"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[dependencies.sdl2]
version = "0.33"
default-features = false

