version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.43.0
    steps:
      - checkout

      - run: apt-get -y install libsdl2-dev

      - run:
          name: Cargo
          command: cargo run

workflows:
  main:
    jobs:
      - build
