version: 2.1

orbs:
  rust: glotrade/rust@0.1.3

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout

      - run: sudo apt-get -y install libsdl2-dev

      - run:
          name: Cargo
          command: cargo run

workflows:
  main:
    jobs:
      - build
